blog-post/blog_post_app/author/forms.py
""" Flask Form """
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email

class RegistrationForm(FlaskForm) :
    """ Registration Form """
    username = StringField("Username: ", validators=[DataRequired(), Length(min=2, max=25)])
    email = StringField("Email: ", validators=[DataRequired(), Email()])
    password = PasswordField("Password: ", validators=[DataRequired()])
    confirm_password = PasswordField("Confirm password: ", validators=[DataRequired()])
    submit = SubmitField("Register")

class LoginForm(FlaskForm) :
    """ Login Form """
    username = StringField("Username: ", validators=[DataRequired(), Length(min=2, max=25)])
    password = PasswordField("Password: ", validators=[DataRequired()])
    remember_me = BooleanField("Remember me")
    submit = SubmitField("Login")

blog-post/blog_post_app/__init__.py
from flask import Flask, render_template
from config import ConfigDev

def create_app(class_config=ConfigDev) :
    """ Create an instance of the blog post app """
    app = Flask(__name__)
    app.config.from_object(class_config)
    
    from blog_post_app.author.routes import author_bp
    from blog_post_app.main.routes import main_bp
    from blog_post_app.post.routes import post_bp
	
    app.register_blueprint(author_bp)
    app.register_blueprint(main_bp)
    app.register_blueprint(post_bp)
    
    app.register_error_handler(404, page_not_found)
	
    return app

def page_not_found(e) :
    """ Page Not Found """
    context = {
        "page_title": "404",
        "main_heading": "Page Not Found - Error 404"
    }
    return render_template("404.html", context=context), 404

blog-post/blog_post_app/author/__init__.py
# Declares auth as a module

blog-post/blog_post_app/author/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from blog_post_app.author.forms import RegistrationForm, LoginForm

author_bp = Blueprint(
    "author_bp",
    __name__,
    template_folder = "templates",
    static_folder = "static"
)

@author_bp.route("/register", methods = ["GET", "POST"])
def registration() :
    """ Register """
    register_form = RegistrationForm()
    if request.method == "POST":
        if register_form.validate_on_submit() :
            flash("Successfully registered!", "success-bg")
            return redirect(url_for("main_bp.home"))
    context = {
        "page_title": "Registration",
        "form": register_form
    }
    return render_template("registration.html", context=context)
    

@author_bp.route("/login", methods = ["GET", "POST"])
def login() :
    """ Login """
    login_form = LoginForm()
    if request.method == "POST":
        if login_form.validate_on_submit() :
            flash("Successfully logged in!", "success-bg")
            return redirect(url_for("main_bp.home"))
    context = {
        "page_title": "Login",
        "form": login_form
    }
    return render_template("login.html", context=context)

blog-post/blog_post_app/main/__init__.py
# Declare main as module

blog-post/blog_post_app/main/routes.py
from flask import abort, Blueprint, redirect, render_template, url_for
from markupsafe import escape

main_bp = Blueprint(
    "main_bp",
    __name__,
    template_folder = "templates",
    static_folder = "static"
)

@main_bp.route("/")
@main_bp.route("/home")
def home() :
    """ Home """
    context = {
        "page_title": "Home",
        "main_heading": "Welcome to my home page!"
    }
    return render_template("home.html", context=context)

@main_bp.route("/about")
def about() :
    """ About """
    context = {
        "page_title": "About",
        "main_heading": "Welcome to my about page!"
    }
    return render_template("about.html", context=context)

@main_bp.route("/page-x/<string:choice>")
def page_x(choice) :
    """ Page x """    
    choice = escape(choice)

    if choice == "h" :
        return redirect(url_for("main_bp.home"))
    elif choice == "a" :
        return redirect(url_for("main_bp.about"))
    else :
        return abort(404)

blog-post/blog_post_app/post/__init__.py
# Declare post as a module

blog-post/blog_post_app/post/routes.py
from flask import abort, Blueprint, render_template
from markupsafe import escape
from blog_post_app.post.posts import posts_list

post_bp = Blueprint(
    "post_bp",
    __name__,
    template_folder = "templates",
    static_folder = "static"
)

@post_bp.route("/post/<int:post_id>")
def post(post_id) :
    """ Post """
    post_id = int(escape(post_id))
    post_item = None
    for post in posts_list :
        if post["id"] == post_id :
            post_item = post
            break
    
    if post_item is None :
        return abort(404)

    context = {
        "page_title": f"Post {post_id}",
        "main_heading": f"Post {post_id} info",
        "post": post_item
    }
    return render_template("post.html", context=context)

@post_bp.route("/list-all-posts")
def list_all_posts() :
    """ List all posts """
    context = {
        "page_title": "Posts",
        "main_heading": "List of All Posts",
        "posts": posts_list
    }
    return render_template("list-all-posts.html", context=context)

blog-post/blog_post_app/routes.py
from flask import Blueprint

blog_post_bp = Blueprint(
    "blog_post_bp", 
    __name__,
    template_folder = "templates",
    static_folder = "static"
)

blog-post/blog_post_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{ context["page_title"] }}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" >
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{{ url_for('main_bp.home') }}">Home</a></li>
                    <li><a href="{{ url_for('main_bp.about') }}">About</a></li>
                    <li><a href="{{ url_for('post_bp.list_all_posts') }}">List of All Posts</a></li>
                    <li><a href="{{ url_for('author_bp.registration') }}">Register</a></li>
                    <li><a href="{{ url_for('author_bp.login') }}">Login</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <h1>{{ context["main_heading"] }}</h1>
            {% block content %}
            {% endblock %}
            {% with messages = get_flashed_messages ( with_categories = true )%}
                {% if messages %}
                    {% for category, message in messages %}
                        <section class='{{ category }}'> {{message}} </section>
                    {% endfor%}
                {% endif %}
            {% endwith %}
        </main>
        <footer>
            <ul>
                <li>Wan Mei TAO</li>
                <li>&copy; 2024</li>
            </ul>
        </footer>
    </body>
</html>